FROM php:7.4-fpm-alpine
MAINTAINER Naba Das <nabad600@gmail.com>
RUN apk add --no-cache \
    apache2-proxy \
    apache2
RUN apk add --update --no-cache libgd libpng-dev libjpeg-turbo-dev freetype-dev
RUN apk add grep \
    git \
    curl \
    vim 
RUN  rm -rf /etc/init.d/*; \
     mkdir /run/apache2; \
     addgroup -g 1000 -S www-data; \
     adduser -G www-data -u 1000 -s /bin/sh -D www-data; \
     sed -rie 's|;error_log = log/php7/error.log|error_log = /dev/stdout|g' /etc/php7/php-fpm.conf 
COPY httpd.conf /etc/apache2/httpd.conf
COPY www.conf /etc/php7/php-fpm.d/www.conf
COPY php.ini /etc/php7/php.ini
COPY scripts /scripts
RUN chmod -R 755 /scripts
CMD ["/scripts/run.sh"]
